Support AVR (Arduino) platform
embassy-rs/critical-section pull request #6
Opened 2021-10-18 03:42 UTC by torrancew

This commit adds support for AVR (Arduino) platforms via the
`avr-device` crate. Due to the nature of the AVR platform & `avr-device`
crate, board-specific features from `avr-device` are re-exported here.

The underlying motivation for this support is to enable further
integration with the greater Embedded Rust ecosystem. As an example,
`embedded-nal` depends upon `heapless`, which in turn depends upon
atomic support, either natively or via `atomic-polyfill`.
`atomic-polyfill` uses `critical-section`, and so enabling AVR support
in this crate has great benefits to the downstream packages that have
come to depend upon `critical-section`.

`avr-device` was adapted to provide `critical-section`-compatible
interrupt semantics in Rahix/avr-device#89, which was released in `avr-device` `v0.3.2`.

To test compilation against this feature, you would use a compatible target JSON
specification (several are available [here](https://github.com/Rahix/avr-hal-template/tree/main/avr-specs)), and enable the corresponding feature.

Example:
```
cargo build --target avr-specs/avr-atmega2560.json --features avr-atmega2560
```

2021-11-02 17:36 UTC, Dirbaio commented
Thanks for the PR and sorry for the late reply. Yes, AVR support is definitely nice to have. The more targets the better!

I have some concerns about the implementation:

- The actual interrupt enable/disable is just [a few `asm` instructions](https://github.com/Rahix/avr-device/blob/main/src/interrupt.rs) common to all AVR chips. It shouldn't be necessary for the user to have to specify the chip via Cargo features. Copypasting the ASM into this crate would make `critical-section` Just Work even if it's used deep in the dependency tree without the user even being aware it exists.
- The `avr-device` is a PAC. PACs are setup so that the build fails if there are multiple major versions in use at once, to forbid doing `Peripherals::take()` multiple times. This is done via this [no_mangle](https://github.com/Rahix/avr-device/blob/main/src/devices/mod.rs#L3). This makes upgrading the `avr-device` major version in `critical-section`'s Cargo.toml a breaking change (major bump) which would be very bad because it splits the ecosystem: every single crate would have to update.

2021-11-14 23:21 UTC, torrancew commented
@Dirbaio Thank you for the feedback! That makes perfect sense to me. Apologies, I'm a bit new to the embedded Rust ecosystem, and didn't realize the third point. I've updated the PR to implement the ASM directly -- LMK if there's any other changes you'd like to see.

2021-11-15 11:57 UTC, Dirbaio requested changes
Looks great! Just one last nit

2021-11-15 11:57 UTC, Dirbaio commented on src/lib.rs
> +#![feature(llvm_asm)]
This will make building on stable Rust fail. You can make it conditional to AVR with `#![cfg_attr(target_arch = "avr", feature(llvm_asm))]`, so only AVR requires nightly.

2021-11-15 11:58 UTC, Dirbaio commented
Oh, also could you add AVR to CI? [here](https://github.com/embassy-rs/critical-section/blob/main/ci.sh).

2022-04-08 02:06 UTC, merged